name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Go mod tidy
      run: go mod tidy
    
    - name: Go fmt
      run: |
        if [ "$(gofmt -s -l . | grep -v vendor/ | wc -l)" -gt 0 ]; then
          echo "Code is not formatted:"
          gofmt -s -l . | grep -v vendor/
          exit 1
        fi
    
    - name: Go vet
      run: go vet $(go list ./... | grep -v /vendor/)
    
    - name: Test
      run: go test -v ./...
    
    - name: Build
      run: go build -v ./...
