name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Build binaries and create archives
      run: |
        mkdir -p bin
        VERSION=${GITHUB_REF#refs/tags/}
        COMMIT=$(git rev-parse --short HEAD)
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        LDFLAGS="-X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE"
        
        # Build and package each platform
        GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o kubectl-aws_nodes .
        tar -czf bin/kubectl-aws-nodes-linux-amd64.tar.gz kubectl-aws_nodes LICENSE
        rm kubectl-aws_nodes
        
        GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o kubectl-aws_nodes .
        tar -czf bin/kubectl-aws-nodes-linux-arm64.tar.gz kubectl-aws_nodes LICENSE
        rm kubectl-aws_nodes
        
        GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o kubectl-aws_nodes .
        tar -czf bin/kubectl-aws-nodes-darwin-amd64.tar.gz kubectl-aws_nodes LICENSE
        rm kubectl-aws_nodes
        
        GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o kubectl-aws_nodes .
        tar -czf bin/kubectl-aws-nodes-darwin-arm64.tar.gz kubectl-aws_nodes LICENSE
        rm kubectl-aws_nodes
        
        # Generate checksums
        cd bin
        sha256sum *.tar.gz > checksums.txt
        cat checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/*.tar.gz
          bin/checksums.txt
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
