name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Build binaries
      run: |
        mkdir -p bin
        VERSION=${GITHUB_REF#refs/tags/}
        COMMIT=$(git rev-parse --short HEAD)
        DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        LDFLAGS="-X main.version=$VERSION -X main.commit=$COMMIT -X main.date=$DATE"
        GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o bin/kubectl-aws_nodes-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o bin/kubectl-aws_nodes-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o bin/kubectl-aws_nodes-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o bin/kubectl-aws_nodes-darwin-arm64 .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
